# docker-compose.yml

version: "3"

services:
  db:
    image: postgres:12
    container_name: db
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    depends_on: 
      db:
        condition: service_healthy